[ru-CresCorp]
repo = "Crescent-Corporation/LimbusCompanyBusRUS"
name = "CresCorp"
authors = ["Knightey", "Disaer", "Mellison", "Mermera"]
flag = "RU"
icon = "https://github.com/Crescent-Corporation/LimbusCompanyBusRUS/raw/LC_branch_ORIGINAL/Localize/Readme/Crescent_Button.png"
format = "auto"
fonts = []

[ru-mtl]
repo = "kimght/LimbusCompanyRuMTL"
name = "MTL"
authors = ["kimght", "DAFTPUSiK", "x1bViolet", "Babkaebpmg", "KJHater"]
flag = "RU"
icon = "https://github.com/kimght/LimbusCompanyRuMTL/raw/main/data/images/logo.png"
format = "new"
localization_asset = "localize_files.zip"
fonts = []

[ru-Divine]
repo = "Divine-Company/DivineCompany_RussianTranslationDepartment"
name = "Divine Company"
authors = ["Helck", "KreeperHLC", "VaNeSS", "Master_1"]
flag = "RU"
icon = "https://github.com/Divine-Company/DivineCompany_RussianTranslationDepartment/raw/main/Icon_Divine.png"
format = "auto"
fonts = []

[ru-RCR]
repo = "EnderDremurr/RCR-LCB"
name = "Rainbus Company Rofls"
authors = ["Rainbus Company Rofls"]
flag = "RU"
icon = "https://github.com/EnderDremurr/RCR-LCB/raw/main/data/images/logo.png"
format = "auto"
fonts = []

[es-DreamsOffice]
repo = "Dreams-Office/LimbusCompanySpanishTranslationTeam"
name = "Dreams Office"
authors = [
  "Mokoutanized",
  "DjPixelES",
  "Oriane",
  "capslockSleep",
  "Herkenni",
  "Nuklear",
  "Frost-12",
  "Kurotomaki",
  "Weeblations",
  "JadedVoid",
  "Seismol76",
  "Polori",
  "DrEnnnnigma",
  "Melky",
  "Kaunto",
  "LuckAfter",
  "Cleoh",
  "DaniUltraReal",
  "Hidalgotraductor",
  "lejoram",
  "Ubanaciel",
  "Wilson2Step",
  "Raum2901",
  "Donki-nari",
  "Laloh-id"
]
flag = "MX"
icon = "https://github.com/Dreams-Office/LimbusCompanySpanishTranslationTeam/raw/main/Localize/Readme/DonQui_Button_Hovered.png"
format = "auto"
fonts = []

[hant-LTM]
repo = "LimbusTraditionalMandarin/storyline"
name = "Limbus Traditional Mandarin"
authors = [
  # Lead
  "薯條",
  # Managers
  "Traxton",
  "小睡一夏",
  "まぅSmallYuan",
  "tool-jx3",
  "未知未知",
  # Proofreaders
  "：이상",
  "阿茶同學",
  "十",
  # Translators
  "동랑",
  "Dango-moshi",
  "Linne1025",
  "蜜絲",
  "동백.",
  "ulofsix"
]

flag = "HANT.png"
icon = "https://avatars.githubusercontent.com/u/200600060"
format = "new"

[[hant-LTM.fonts]]
url = "https://github.com/LimbusTraditionalMandarin/font/releases/download/1744630853/SarasaGothicTC-Bold.ttf"
hash = "44563efaea921914d58e42bac4495881"
name = "Context/ContextFont.ttf"

[[hant-LTM.fonts]]
url = "https://github.com/LimbusTraditionalMandarin/font/releases/download/1744630853/SarasaGothicTC-Bold.ttf"
hash = "44563efaea921914d58e42bac4495881"
name = "Title/TitleFont.ttf"

[zh-CN]
repo = "LocalizeLimbusCompany/LocalizeLimbusCompany"
name = "Localize Limbus Company"
authors = ["Limbus Localize Company"]
flag = "CN"
icon = "https://cdn.zeroasso.top/img/logo.png"
format = "auto"

[[zh-CN.fonts]]
url = "https://raw.githubusercontent.com/LocalizeLimbusCompany/LocalizeLimbusCompany/refs/heads/main/Fonts/ChineseFont.ttf"
hash = "b1af87d9b8a3975e58b9a25a0c04f7b4"
name = "Context/ChineseFont.ttf"

[[zh-CN.fonts]]
url = "https://raw.githubusercontent.com/LocalizeLimbusCompany/LocalizeLimbusCompany/refs/heads/main/Fonts/ChineseFont.ttf"
hash = "b1af87d9b8a3975e58b9a25a0c04f7b4"
name = "Title/ChineseFont.ttf"

[ptbr-TeamPato]
repo = "2tsunami5/Team-PATO_LimbusCompanyBrasil"
name = "LCBPATO"
authors = ["Team PATO"]
flag = "BR"
icon = "https://raw.githubusercontent.com/2tsunami5/Team-PATO_LimbusCompanyBrasil/LCBPATO/team_resources/img/434949545-0aa4ce11-2885-4328-8c0d-beeb0fa13169.png"
format = "auto"

[[ptbr-TeamPato.fonts]]
url = "https://github.com/2tsunami5/Team-PATO_LimbusCompanyBrasil/raw/refs/heads/LCBPATO/team_resources/font/BebasNeue-Regular.ttf"
hash = "b2b293064f557c41411aac04d6f6710d"
name = "Context/BebasNeue-Regular.ttf"

[[ptbr-TeamPato.fonts]]
url = "https://github.com/2tsunami5/Team-PATO_LimbusCompanyBrasil/raw/refs/heads/LCBPATO/team_resources/font/BebasNeue-Regular.ttf"
hash = "b2b293064f557c41411aac04d6f6710d"
name = "Title/BebasNeue-Regular.ttf"

[ptbr-CLT]
repo = "Eike-Felipe/CLT-District_Limbus-Brasil"
name = "CLT-LCBR"
authors = ["CLT District"]
flag = "BR"
icon = "https://raw.githubusercontent.com/Eike-Felipe/CLT-District_Limbus-Brasil/main/loc_assets/Icon/CLT_District.png"
format = "auto"

[[ptbr-CLT.fonts]]
url = "https://raw.githubusercontent.com/Eike-Felipe/CLT-District_Limbus-Brasil/refs/heads/main/loc_assets/Fonts/Context/ContextFont.otf"
hash = "46b0c48afd8b0ddc2ed4fcbb2df81d8b"
name = "Context/ContextFont.otf"

[[ptbr-CLT.fonts]]
url = "https://raw.githubusercontent.com/Eike-Felipe/CLT-District_Limbus-Brasil/refs/heads/main/loc_assets/Fonts/Title/TitleFont.otf"
hash = "a4e82e00d0643abcd1ee10faae27dbd2"
name = "Title/TitleFont.otf"

[th-stlinx]
repo = "stlinx/LocalizeLimbusTH"
name = "LimbusThai by stlinx"
authors = ["stlinx", "JoshWaltz49", "Asunokun"]
flag = "TH"
icon = "https://raw.githubusercontent.com/stlinx/Limbus-loader/main/icon.jpg"
format = "auto"
fonts = []

[it-espresso]
repo = "Laetaria/LocalizeLimbusIT"
name = "Espresso Office"
authors = [
  "flowerssummerr",
  "Eremitaviola",
  "Ballastedmarco91",
  "KoilaKarpaKoi",
  "GhostyTricker",
  "Cimone",
  "SirPapera",
  "Veldia",
  "Dottore"
]
flag = "IT"
icon = "https://raw.githubusercontent.com/Laetaria/UfficioEspresso/main/IMG_0570.png"
format = "auto"
fonts = []

[hant-RHOY]
repo = "user-unknown-0711/ParatranzUploader"
name = "Retirement Home Old Yard"
authors = ["Retirement Home Old Yard"]

flag = "HANT.png"
icon = "https://raw.githubusercontent.com/user-unknown-0711/ParatranzUploader/main/resources/icons/RHOY.png"
format = "new"
localization_asset = "localize_files.zip"

[[hant-RHOY.fonts]]
url = "https://github.com/LimbusTraditionalMandarin/font/releases/download/1744630853/SarasaGothicTC-Bold.ttf"
hash = "44563efaea921914d58e42bac4495881"
name = "Context/ContextFont.ttf"

[[hant-RHOY.fonts]]
url = "https://github.com/LimbusTraditionalMandarin/font/releases/download/1744630853/SarasaGothicTC-Bold.ttf"
hash = "44563efaea921914d58e42bac4495881"
name = "Title/TitleFont.ttf"
